### ISSUE TITLE
clients fail with a heartbeat exception despite ongoing traffic from server

### ISSUE THREAD

**Issue by michaelplaing** [gmr/rabbitpy#70] opened 2015-04-11 22:18 UTC
I think this is because the server sends traffic and therefore does not need to send a heartbeat.

A workaround is to hack IO.on_read to set the Channel0._last_heartbeat to time.time() if the frame is not for Channel0.

**Comment by michaelplaing** [comment] 2015-04-12 12:23
I had another failure after 14 hours of testing multiple apps, so maybe my hack is not complete...

Pivotal responded thus:
On 11 April 2015 at 13:49:06, Laing, Michael (michael.laing@nytimes.com) wrote:
> . Once heartbeats have been negotiated, are they always sent
> by the server on the interval or are they sent only if other traffic
> has not been sent by the server in the interval?

They are always sent at half the timeout intervals but can be paused in some circumstances.
However, both peers must treat any traffic as heartbeats (or well, connection activity).

> . Are heartbeats always sent by the server per connection and
> on the channel that negotiated the connection (channel 0 in my
> case)?

Yes.

Channel 0 is special: connection negotiation happens on it, heartbeats are sent on it.
Applications cannot use it.

Relevant implementation bits:

 * https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_reader.erl#L1063-1069
 * https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_heartbeat.erl

Let me know if you have more questions.
--
MK

Staff Software Engineer, Pivotal/RabbitMQ

**Comment by gmr** [comment] 2015-04-13 13:53
I'll try and get this addressed this week.

**Comment by elotc** [comment] 2015-07-27 10:54
Hi Gavin, I'm still having issues with the head code.

I have a simple publisher publishing every 10 secs to a topic exchange. So no heartbeats are sent as traffic is flowing continually. My consuming client gets a connection reset after 15 mins - rabbitmq logs:

=INFO REPORT==== 27-Jul-2015::11:18:21 ===
accepting AMQP connection <0.26763.0> (127.0.0.1:34141 -> 127.0.0.1:5672)

=INFO REPORT==== 27-Jul-2015::11:18:23 ===
accepting AMQP connection <0.26779.0> (127.0.0.1:34142 -> 127.0.0.1:5672)

=ERROR REPORT==== 27-Jul-2015::11:33:21 ===
closing AMQP connection <0.26763.0> (127.0.0.1:34141 -> 127.0.0.1:5672):
{heartbeat_timeout,running}

Looking through the debug logs I dont see any "base|write_frame|Writing frame: Heartbeat" calls - I guess because there are no heartbeats being sent as traffic is continually flowing.
$ grep -i -e heartbeat -e write_frame do_sub.log
2015-07-27 11:18:21,892|DEBUG|12348|base|write_frame|Writing frame: ProtocolHeader
2015-07-27 11:18:21,943|DEBUG|12348|base|write_frame|Writing frame: Connection.StartOk
2015-07-27 11:18:21,957|DEBUG|12348|base|write_frame|Writing frame: Connection.TuneOk
2015-07-27 11:18:21,960|DEBUG|12348|base|write_frame|Writing frame: Connection.Open
2015-07-27 11:18:22,013|DEBUG|12348|heartbeat|_start_timer|Started a heartbeat timer that will fire in 300 sec
2015-07-27 11:18:22,024|DEBUG|12348|base|write_frame|Writing frame: Channel.Open
2015-07-27 11:18:22,051|DEBUG|12348|base|write_frame|Writing frame: Exchange.Declare
2015-07-27 11:18:22,070|DEBUG|12348|base|write_frame|Writing frame: Queue.Declare
2015-07-27 11:18:22,110|DEBUG|12348|base|write_frame|Writing frame: Queue.Bind
2015-07-27 11:18:22,134|DEBUG|12348|base|write_frame|Writing frame: Basic.Consume
2015-07-27 11:23:22,037|DEBUG|12348|heartbeat|_check|Data has been received, exiting heartbeat check
2015-07-27 11:23:22,039|DEBUG|12348|heartbeat|_start_timer|Started a heartbeat timer that will fire in 300 sec
2015-07-27 11:28:22,044|DEBUG|12348|heartbeat|_check|Data has been received, exiting heartbeat check
2015-07-27 11:28:22,046|DEBUG|12348|heartbeat|_start_timer|Started a heartbeat timer that will fire in 300 sec
2015-07-27 11:33:22,052|DEBUG|12348|heartbeat|_check|Data has been received, exiting heartbeat check
2015-07-27 11:33:22,054|DEBUG|12348|heartbeat|_start_timer|Started a heartbeat timer that will fire in 300 sec



I've rerun the tests using pika and I can see the heartbeat being sent back to rabbitmq every 580 secs when data is flowing constantly.

2015-07-27 10:38:38,713|DEBUG|11591|heartbeat|_send_heartbeat_frame|Sending heartbeat frame
2015-07-27 10:48:18,724|DEBUG|11591|heartbeat|_send_heartbeat_frame|Sending heartbeat frame
2015-07-27 10:57:58,738|DEBUG|11591|heartbeat|_send_heartbeat_frame|Sending heartbeat frame
2015-07-27 11:07:38,750|DEBUG|11591|heartbeat|_send_heartbeat_frame|Sending heartbeat frame

Should the heartbeat.Checker._check() method send a heartbeat frame if data has been received?

Also I think there may be a bit of a race condition if the consumer checker timer triggers before a heartbeat is received if traffic is flowing and then stops - self._last_heartbeat is initialised to 0 and only set to a proper time if a heartbeat is received - the snippet below shows that its still at 0 when this check is done ... let me try to reproduce but I guess maybe the last_heartbeat time should be updated on Data Receive???

2015-07-24 22:57:59,297|DEBUG|11529|heartbeat|_check|Data has been received, exiting heartbeat check
2015-07-24 22:57:59,298|DEBUG|11529|heartbeat|_start_timer|Started a heartbeat timer that will fire in 300 sec
2015-07-24 23:02:59,300|DEBUG|11529|heartbeat|_check|Checking for heartbeat, last: 1437775379 sec ago, threshold: 600
2015-07-24 23:02:59,301|ERROR|11529|heartbeat|_check|Have not received a heartbeat in 1437775379 seconds


Hope this all makes sense - if not let me know and I'll try and clarify what I'm seeing.

Brendan

**Comment by gmr** [comment] 2016-10-28 00:22
Heartbeating has been completely changed for 1.0 and this problem should be go away.

**Closed by gmr** 2016-10-28 00:22 UTC
