### ISSUE TITLE
Only one channel gets connectionResetException

### ISSUE THREAD

**Issue by rejoc** [gmr/rabbitpy#81] opened 2015-10-02 09:28 UTC
Suppose you have multiple channels, each in one thread, sharing a unique connection, and consuming messages.

When the connection breaks (can be simulated by hitting the "Force close" button on rabbitMQ manager), only one channel gets the exception. The others are still waiting for messages :-(

**Comment by gmr** [comment] 2016-10-28 00:21
I don't have a proposed fix for this behavior. I can't figure out what threads you're invoking what API methods from. I would probably implement some sort of exception management and shared state behavior. Do you know of any libraries that share a common base connection and raise an exception to all threads?

**Comment by eandersson** [comment] 2016-10-28 00:38
I support the following type of scenario.
https://github.com/eandersson/amqpstorm/blob/master/examples/scalable_consumer.py

Basically all channels share the same connection, while the main thread manages the connection. When a connection dies, all channels catch the exception and close, once that is done, a new connection is opened.

Although, not sure if my way of dealing with this would carry over easily to rabbitpy.

**Comment by gmr** [comment] 2016-10-28 01:00
The way I read the issue is that I believe they're expecting the same exception to be raised in every thread, which I don't know which threads to raise it on. Instead different exceptions are raised based upon what's going on in each of the objects in the threads.

rabbity has a similar behavior, when the connection is closed, the channels are torn down, exceptions raised, etc. It just happens to be the active thread that gets the connection closed and the others will get other exceptions based upon the action they were taking.

Anyway, here's the output of a multi-threaded app that's consuming and doing stuff across threads with a remote close:

```python
DEBUG:rabbitpy.base:Writing frame: Basic.Ack
DEBUG:rabbitpy.base:Waiting on <class 'pamqp.specification.Basic.Deliver'> frame(s)
DEBUG:rabbitpy.channel0:Received frame: 'Connection.Close'
WARNING:rabbitpy.channel0:RabbitMQ closed the connection (320): b'CONNECTION_FORCED - Closed via management plugin'
DEBUG:rabbitpy.base:Channel0 setting state to 'Closed'
DEBUG:rabbitpy.connection:State: 'Open'
DEBUG:rabbitpy.base:Connection setting state to 'Closing'
DEBUG:rabbitpy.base:IO setting state to 'Closing'
DEBUG:rabbitpy.events:Event is already set: Socket Closed
DEBUG:rabbitpy.base:IO setting state to 'Closed'
DEBUG:rabbitpy.base:Connection setting state to 'Closed'
DEBUG:rabbitpy.io:Exiting due to closed socket
DEBUG:rabbitpy.io:Exiting IOLoop.run
DEBUG:rabbitpy.io:Exiting IO.run
DEBUG:rabbitpy.base:Interrupting the wait on frame
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "example.py", line 60, in fill_queue
    rabbitpy.Message(self.channel, body_value="test?").publish(exchange="test_resp_enchange.e", routing_key="test_resp_queue")
  File "/Users/gmr/Source/rabbitpy/rabbitpy/message.py", line 284, in publish
    self.channel.write_frames(frames)
  File "/Users/gmr/Source/rabbitpy/rabbitpy/base.py", line 261, in write_frames
    if self._can_write():
  File "/Users/gmr/Source/rabbitpy/rabbitpy/base.py", line 283, in _can_write
    raise exceptions.ConnectionNotOpen()
rabbitpy.exceptions.ConnectionNotOpen: The connection is not open

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "example.py", line 51, in get_rx
    for item in self.in_q:
  File "/Users/gmr/Source/rabbitpy/rabbitpy/amqp_queue.py", line 195, in consume
    message = self.channel._consume_message()
  File "/Users/gmr/Source/rabbitpy/rabbitpy/channel.py", line 311, in _consume_message
    frame_value = self._wait_on_frame([spec.Basic.Deliver])
  File "/Users/gmr/Source/rabbitpy/rabbitpy/base.py", line 467, in _wait_on_frame
    self._check_for_exceptions()
  File "/Users/gmr/Source/rabbitpy/rabbitpy/base.py", line 309, in _check_for_exceptions
    raise exception
rabbitpy.exceptions.AMQPConnectionForced: b'CONNECTION_FORCED - Closed via management plugin'

Traceback (most recent call last):
  File "example.py", line 87, in <module>
    test()
  File "example.py", line 81, in test
    tester.interrupt()
  File "example.py", line 64, in interrupt
    self.in_q.stop_consuming()
  File "/Users/gmr/Source/rabbitpy/rabbitpy/amqp_queue.py", line 324, in stop_consuming
    raise exceptions.NotConsumingError()
rabbitpy.exceptions.NotConsumingError: No active consumer to cancel
```

**Closed** 2019-08-06 08:27 UTC
